CHANGELOG.md
core/src/lib.rs
debug/src/dim2.rs
examples/demo.rs
rapier/src/bodies.rs
rapier/tests/bodies.rs

Add capsule shape

---

CHANGELOG.md
Cargo.toml
core/src/lib.rs
debug/src/dim2.rs
examples/demo.rs
rapier/src/bodies.rs

Add cuboid shape

---

CHANGELOG.md
Cargo.toml
core/src/lib.rs
examples/demo.rs
rapier/src/bodies.rs
rapier/src/body.rs
rapier/src/lib.rs
rapier/tests/body_types.rs
src/lib.rs

Add support for static bodies.
To make a body static, add the component `BodyType::Static`.
Resolves #7

feat: Static bodies

---

CHANGELOG.md
core/src/lib.rs
examples/demo.rs
rapier/src/body.rs
rapier/tests/body_types.rs

feat: Add sensor

---

Cargo.toml
examples/debug.rs

Suggested by @faassen in the bevy discord. I think it is a good Idea to demonstrate the debug feature. And it can make easier the development when supporting more shapes to render.

docs(examples): Add a debug example

---

.github/workflows/build.yml
CHANGELOG.md
Cargo.toml
core/Cargo.toml
core/src/ext.rs
core/src/gravity.rs
core/src/lib.rs
core/src/utils.rs
core/src/velocity.rs
debug/Cargo.toml
debug/src/dim2.rs
debug/src/lib.rs
rapier/Cargo.toml
rapier/src/body.rs
rapier/src/convert.rs
rapier/src/lib.rs
rapier/src/pipeline.rs
rapier/src/velocity.rs
rapier/tests/resources.rs
src/lib.rs

All components now implement `Default` and `Reflect`, so it should be possible to use heron components in serialized scene.
This should be especially helpful for hot-reloading.

feat: Register all components for bevy reflection

---

core/src/ext.rs
core/src/lib.rs
core/src/velocity.rs
rapier/src/lib.rs
src/lib.rs

I found some grammar mistakes on docs.rs and decided to fix most of them.

docs: Fix grammar mistakes on docs.rs

---

CHANGELOG.md
core/src/lib.rs
rapier/src/body.rs
rapier/tests/friction.rs

feat!: Support defining friction

---

core/src/physics_time.rs
rapier/src/lib.rs
rapier/src/pipeline.rs
rapier/tests/resources.rs

refactor: Improve efficiency of how the time scale is applied

---

core/src/layers.rs
core/src/lib.rs
macros/src/lib.rs
rapier/Cargo.toml
rapier/src/body.rs
rapier/src/convert.rs
rapier/src/lib.rs
rapier/src/pipeline.rs
rapier/src/shape.rs
rapier/src/velocity.rs
rapier/tests/bodies.rs
rapier/tests/body_types.rs
rapier/tests/children_collision_shapes.rs
rapier/tests/constraints.rs
rapier/tests/friction.rs
rapier/tests/layers.rs
rapier/tests/restitution.rs
rapier/tests/velocity.rs
src/lib.rs
tests/macros.rs

Rapier 0.9

---

guide/src/layers.md

The latest rapier version supports 32 layers.

Update Guide to Indicate 32 Layer Maximum

---

debug/src/lib.rs

fix: Invasive scaling of all entities in debug mode

---

README.md

Fixed missing : in line 45 of readme

---

CHANGELOG.md
core/src/lib.rs
debug/src/dim3.rs
debug/src/shape3d_wireframe.rs
examples/debug_3d.rs
rapier/src/shape.rs

Add cylinder collision shape

---

CHANGELOG.md
core/src/lib.rs
rapier/src/lib.rs
rapier/tests/bodies.rs

Fix #165.
Thanks @YannikSc for the bug report.

fix: Despawn not working when simulation is paused

---

.github/workflows/build.yml
Cargo.toml
README.md
rapier/Cargo.toml
src/lib.rs

Just a quick addition to pass on the determinism flag on to rapier 😄

feat: enhanced determinism feature flag

---

core/src/layers.rs

feat: add CollisionLayers::all_groups and CollisionLayers::all_masks

---

.github/workflows/build.yml
Cargo.toml
README.md
debug/Cargo.toml
debug/src/lib.rs
examples/debug_3d.rs
src/lib.rs

feat(debug): reintroduce the 3d debug renderer (was removed when migrating to bevy 0.6)

---

core/src/layers.rs

Harmless change, I need this to make nicer tests for #224 :)

feat: make `CollisionLayers::none` and `CollisionLayers::from_bits` const functions

---

rapier/src/lib.rs

fix: children lagging behind when the parent rigid body is moved by physics

---

core/src/velocity.rs

@cark, do you think this documentation makes it clearer?

docs: clarify that the velocity component can also be used to read the velocity

---

rapier/src/lib.rs

fix #251.
Thanks @cark for the bug report.

fix: acceleration still applied while PhysicsTime is paused
