rapier/src/lib.rs

I tried creating a new `BodyHandle` but was unable to.
I didn't want to make fields public, so I created a constructor for creating a new `BodyHandle` object.

Added a BodyHandle constructor

---

CHANGELOG.md
core/Cargo.toml
core/src/ext.rs
core/src/lib.rs
debug/src/lib.rs
rapier/src/lib.rs
src/lib.rs

The physics steps run at a fixed rate (60 updates per second by default). They are therefore not in sync with the frame update (that runs as many times per second as possible).
But a user may want (and sometime have to) run system synchronously with the physics step. Generally either before (when modifying position/velocities) or after the physiscs step (when reading the output).
This PR exposes the following stages:
* `stage::ROOT`  **schedule** stage that runs at a fixed rate (60 updates per second by default)
* `stage::UPDATE` a **child** (parallel) system stage that runs before the physics step. 
It also add the `add_physiscs_system` extension function on `AppBuilder`: to make simpler to add systems that should be synchronized with the physics steps.
**This is a breaking change:** …

feat!: Provide stage to allow running systems before/after each physics step

---

CHANGELOG.md
core/src/constraints.rs
core/src/ext.rs
core/src/lib.rs
rapier/src/body.rs
rapier/src/lib.rs
rapier/tests/constraints.rs
src/lib.rs

Allow to lock rotation around axes.
Resolves #53

feat: RotationContraints component

---

CHANGELOG.md
core/src/lib.rs
debug/Cargo.toml
debug/src/dim2.rs
examples/debug.rs
rapier/src/body.rs
rapier/src/convert.rs
src/lib.rs

I introduce a new Body type. I've extended the debug renderer to show it as well.
See #59 for a bunch of things I'm not happy about yet. In brief summary:
* I wrote convert code outside of `convert.rs`. This also results in unused import warnings for `body.rs` when I build the demo. (I also see that this breaks the PR checks)
* it could be nice to have a better way to convert a slice of Vec3 to a slice of Vec2 in the implementation of `dim2.rs`
* building a convex hull may fail, which I've hacked around with using `unwrap()`. What would be a better error handling mechanism?

feat!: ConvexHull collision shape

---

rapier/src/body.rs
rapier/src/lib.rs

Since bevy 0.5 the order of execution of systems are no longer guaranteed in single-threaded system stages.
This has led to a tiny issue in heron, that may update the rapier world before the transform propagation system has run. The rapier world will eventually be correctly updated on the next frame. But that's one frame later than it should.
This PR fixes this frame-delay by ensuring the transform propagation always run before updating the rapier world. It also use the opportunity to simplify (a tiny bit) the internal heron stages/system organization.

fix: Frame delay after a spawn/update of the entity transform

---

Cargo.toml
core/src/events.rs
core/src/layers.rs
core/src/lib.rs
examples/demo.rs
examples/events.rs
guide/src/SUMMARY.md
guide/src/events.md
rapier/src/convert.rs
rapier/src/pipeline.rs
rapier/src/shape.rs
rapier/tests/events.rs

Resolve #99 
The `CollisionEvent` now contains a pair of `CollisionData` instead of a pair of `Entity`.
Each `CollisionData` contains:
* The entity of the `RigidBody`
* The entity of the `CollisionShape`
* The `CollisionLayers`

feat!: More data in collision events

---

core/src/lib.rs
examples/collision_shapes_in_child_entity.rs
guide/src/collision_shapes_in_child_entity.md
rapier/src/body.rs
rapier/src/lib.rs
rapier/src/shape.rs
rapier/tests/sensor_shape.rs

Resolve #98
Add a `SensorShape` component that can mark a single collision shape as being a sensor. Even if that shape is attach to a non-sensor rigid body.
That'll make easier to define complex entities with both physics collision shapes and sensors.

feat: SensorShape component to mark individual collision shape as sensor

---

core/src/ext.rs
core/src/lib.rs
core/src/step.rs
debug/src/dim2.rs
debug/src/lib.rs
guide/src/SUMMARY.md
guide/src/interaction.md
rapier/src/lib.rs
rapier/src/pipeline.rs
rapier/src/velocity.rs
rapier/tests/acceleration.rs
rapier/tests/bodies.rs
rapier/tests/body_types.rs
rapier/tests/children_collision_shapes.rs
rapier/tests/constraints.rs
rapier/tests/density.rs
rapier/tests/events.rs
rapier/tests/friction.rs
rapier/tests/layers.rs
rapier/tests/restitution.rs
rapier/tests/sensor_shape.rs
rapier/tests/velocity.rs
src/lib.rs

Resolve #107 
Resolve #81 (because there is no need for `add_physics_system` anymore`)
* The physics step rate is not defined on the plugin type anymore. It is replaced by a `PhysicsSteps` resource.
* The `IntegrationParameters` can no longer be defined when installing the plugin. The `IntegrationParameters` should should be inserted/mutated instead.
* The `Velocity` and `Transform` are now updated during the `CoreStage::PostUpdate`. If a user-system should run *after* the physics update, it should explicitly declares that dependency using the `PhysicsSystem` labels.
The physics steps will now run *at most* once per frame.
At high* FPS the behavior hasn't changed. The physics step will not run on each frame.
At low* FPS the behavior is now different, and the physics step will run at most …

feat! Runs physics step at most once per frame

---

core/src/lib.rs
debug/src/dim2.rs
examples/debug.rs
rapier/src/shape.rs

Resolves #62 
Some notes:
- I went with a `Vec<Vec<f32>>` to define the heights, both in 2D and 3D (and only take the first sub-vec in account in 2D). I couldn't get `#[cfg(features)]` to work as I wanted
- I'm not sure about the debug implementation, because I don't know much about lyon. I'll probably add a heightfield to the `debug` example to see if it does what I expect.
- The scale that rapier expects is actually more the dimensions of the field, so I had to do a little conversion.
- Also, it looks like rapier/parry always centers the heightfield. Is there anything I need to do to update the transform of a collision shape in rapier when it is updated in bevy?

Implement a HeightField collision shape

---

.github/workflows/build.yml
Cargo.toml
build.rs
rapier/Cargo.toml
rapier/build.rs
rapier/src/acceleration.rs
rapier/src/body.rs
rapier/src/convert.rs
rapier/src/lib.rs
rapier/src/velocity.rs
rapier/tests/acceleration.rs
rapier/tests/bodies.rs
rapier/tests/body_types.rs
rapier/tests/children_collision_shapes.rs
rapier/tests/constraints.rs
rapier/tests/density.rs
rapier/tests/events.rs
rapier/tests/friction.rs
rapier/tests/layers.rs
rapier/tests/resources.rs
rapier/tests/restitution.rs
rapier/tests/sensor_shape.rs
rapier/tests/velocity.rs
src/lib.rs
tests/macros.rs

Currently, the heron crate doesn't expose anything unless either the 2D or 3D features are enabled, but enabling either of those features also enables the debug renderer. This makes it impossible to use heron without enabling the debug rendering crates.
My projects use Bevy Retrograde, which uses a custom renderer on top of Bevy that won't compile when bevy's rendering features are enabled. Because the debug crates require Bevy's rendering features, there's no combination of features under which I can compile heron for use in Bevy Retrograde.
This change makes it required to pass in the `debug-2d` or `debug-3d` features in order to actually include the `heron_debug`. This allows me to run my project without including bevy's rendering features.
I'm not sure this is the best way to do it …

Use Separate Cargo Features for Debug 2D and 3D

---

rapier/src/body.rs
rapier/tests/velocity.rs

When adding a rigid body to a 2D object, the Bevy transform update system will reset any translation z value that I have set on the 2D object to 0. This update perserves the 2D Z translation set by the user so that the 2D layers will still work correctly after adding a rigid body to them.
Depends on #118.

Preserve 2D Z Translation

---

.github/workflows/build.yml
core/Cargo.toml
debug/src/dim2.rs
debug/src/lib.rs
rapier/src/acceleration.rs
rapier/src/lib.rs
rapier/src/pipeline.rs
rapier/src/shape.rs
rapier/tests/acceleration.rs
rapier/tests/bodies.rs
rapier/tests/body_types.rs
rapier/tests/children_collision_shapes.rs
rapier/tests/constraints.rs
rapier/tests/density.rs
rapier/tests/events.rs
rapier/tests/friction.rs
rapier/tests/layers.rs
rapier/tests/resources.rs
rapier/tests/restitution.rs
rapier/tests/sensor_shape.rs
rapier/tests/utils/mod.rs
rapier/tests/velocity.rs
release.yml

Fix #124 
`heron_rapier` no longer exports the rapier as `rapier` but as either `rapier2d` or `rapier3d` (or both) depending on the feature flags.

fix!: Compilation errors for 3d users

---

core/src/lib.rs
core/src/step.rs
rapier/src/pipeline.rs
rapier/src/velocity.rs

I'm not sure if I'm missing some caveats or something, but I like the variable timestep strategy because the simulation speed is stable regardless of the framerate. That way, even if some machines can only run at 30 fps, it won't cause a physics slowdown when the physics step is set to 58 fps to optimize for players who can run the game at 60 fps. Or even for players who's FPS might drop temporarily.

Implement Variable Timestep Mode for PhysicsSteps

---

core/src/lib.rs
debug/Cargo.toml
debug/src/dim2.rs
examples/collision_shapes_in_child_entity.rs
examples/debug.rs
examples/demo.rs
examples/events.rs
examples/layers.rs
examples/quickstart.rs
examples/ray_casting.rs
rapier/src/pipeline.rs
rapier/src/shape.rs
tests/macros.rs

I needed rounded convex hulls for my project so here it is! I also added rounded cuboids because I _might_ need them and because they were easy.
I implemented debug rendering for rounded cubes and that works perfectly, but it's not worth my time currently to implement debug rendering for rounded convex hulls. I don't quite know how to do the math to make that one work right. As an interim solution, I simply rendered circles at each of the convex hull's points with hulls border radius. This at least gives an impression of the effect that the border radius has, even if it is not fully accurate.
Let me know if there are any problems!

Implement Rounded Cuboids and Convex Hulls

---

CHANGELOG.md
Cargo.toml
core/Cargo.toml
core/build.rs
core/src/lib.rs
debug/src/dim2.rs
debug/src/dim3.rs
debug/src/shape3d_wireframe.rs
examples/debug_3d.rs
rapier/Cargo.toml
rapier/src/shape.rs

Note: I didn't add `#[non_exhaustive]` to `CollisionShape` **because of the `match` in `rapier/src/shape.rs` line 236**. It would otherwise require adding a `_ => panic!("shape not supported"),` branch to the match expression. I thought it would be more questionable than not adding `#[non_exhaustive]`.

Add cone shape

---

CHANGELOG.md
core/src/lib.rs
rapier/src/lib.rs
rapier/src/shape.rs
src/lib.rs

This PR implements a (draft so far) support for custom collision shapes. The definition of the custom collision shape at the core is abstract from a backend implementation (i.e. `rapier`), but the backend can define the type it supports.
The goal is to enable projects to tighter integrate with backends (in the current case - just `rapier`) where needed - for instance, to use a currently unsupported collision shape - while not coupling the core with any particular backend.
Please take a look, and if you like the idea I can quickly beautify this into a production-ready form.

Support custom collision shapes

---

README.md

This PR updates the README.md example based on changes introduced with bevy `0.6`.
Namely:
- bevy `App` is now constructed with `new` (as opposed to `build`).
- Removal of now unneeded `.system()` call.

docs(readme): update example to bevy 0.6 syntax

---

core/src/lib.rs
debug/src/dim2.rs
debug/src/dim3.rs
debug/src/lib.rs
examples/collision_shapes_in_child_entity.rs
examples/debug_2d.rs
examples/demo.rs
examples/events.rs
examples/layers.rs
examples/quickstart.rs
examples/ray_casting.rs
rapier/src/lib.rs
rapier/src/pipeline.rs
rapier/tests/events.rs

I just removed all `.system()` calls, no longer necessary after 0.6.

refactor: remove all .system()

---

core/Cargo.toml
core/src/events.rs
rapier/src/pipeline.rs
rapier/tests/events.rs

Adds normal data from [`ContactManifoldData::normal`](https://docs.rs/rapier2d/0.11.1/rapier2d/geometry/struct.ContactManifoldData.html#structfield.normal) to the [`CollisionData`](https://docs.rs/heron/1.1.0/heron/struct.CollisionData.html) struct.
- Normal vector added to collision data
- I had to remove `Copy` from `CollisionData` due to the normals being in a `Vec<Vec2>`. We could just provide the first normal Vec2 as an `Option<Vec2>`, but I'm not sure whats the best option for this.
---
Fixes https://github.com/jcornaz/heron/issues/188

feat!: add normals to `CollisionData` in events

---

core/src/collision_from_mesh.rs

The `collision-from-mesh` feature (#190) would cause the plugins to fail if there is no mesh assets resource. 
That is especially problematic for testing, when one may have enabled the `collision-from-mesh` feature, but still want to avoid using the render plugin in tests.
This change makes sure the `collision-from-mesh` feature does not fail if there is no mesh asset resource. Obviously, without a mesh asset, no collision will be generated from meshes.
cc: @Shatur

fix(collision-from-mesh): don't fail if there is no render plugin registered

---

core/src/events.rs
rapier/Cargo.toml
rapier/src/pipeline.rs

Resolve #206 
*This may cause type inference problems*, but is nevertheless considered a minor change. 
This is because it can easily be mitigated *before* updating to the latest version by explicitly declaring the type instead of relying on the type inference.
Fore more information about why this type of change is considered minor see: https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md#minor-change-generalizing-to-generics

feat: let `CollisionData::new` accept any implementation of `IntoIterator<Item=Vec2>`

---

core/src/collision_from_mesh.rs
core/src/lib.rs

I noticed that all other Heron types implement `Reflect`. So I added it to `PendingConvexCollision`.

feat: implement Reflect for PendingConvexCollision

---

Cargo.toml
core/Cargo.toml
debug/Cargo.toml
rapier/Cargo.toml

Previously used `render` feature is a [group](
https://github.com/bevyengine/bevy/blob/a291b5aaedb4affcb31df2e2e63cb0c665ffb24a/Cargo.toml#L35-L43) that contains unneeded stuff, like `bevy_ui` or `bevy_text`. Specified features in this PR is the required minimum. You can read more about in in this issue: https://github.com/bevyengine/bevy/issues/4202

refactor: cleanup unused dependencies

---

core/src/collision_from_mesh.rs

This PR adds an additional field to the `PendingConvexCollision` to set collision layers. I realized that setting default collision is needed only for the generated collision. In all other cases user can define needed collision layer explicitly. Closes #217.

feat: allow to define layers for collision shapes generated by `PendingConvexCollision`

---

core/src/colliding_entities.rs
core/src/collisions.rs
core/src/lib.rs
src/lib.rs

Closes #207.
I added a component that automatically filled with colliding object entities.
Things to discuss:
* I used `CollidingEntities` because the suggested `Collision` could be confusing (and [already used in Bevy](https://docs.rs/bevy/latest/bevy/sprite/collide_aabb/enum.Collision.html), but not in prelude). Is this okay name?
* Should we provide `Deref` for `CollidingEntities`?

feat: colliding entities component

---

core/src/collisions.rs
core/src/events.rs

Currently the `Collisions` component only exposes the entities present in a collision, but there is additional useful information available, such as the collision normals. This change exposes the `CollisionData` object in the `Collisions` component.
Additionally, the collision normals were captured as `Vec2`s, dropping the Z component. I swapped to a `Vec3`, zeroing the Z component when in 2D.

feat: expose CollisionData in Collisions component

---

rapier/src/pipeline.rs

The docs for `shape_cast` say `end_position` instead of `ray`, but the internal usage of the parameter is a ray, not the end position of the shape. This is consistent with the docs for `cast_ray`.
Big thanks to @mijalk0 for helping me figure this out. (Because it said `end_position` I thought I needed to pass the end position of the shape cast)

docs: fix inaccurate parameter documentation of `shape_cast`

---

README.md

Remove comment about `nalgebra` and `rapier` from comparison to `bevy_rapier`.
There may still be parts of `bevy_rapier` that expose `nalgebra`/`rapier` but I could not find an API that that `heron` also has that does.
At the very least I don't think this line accurately represents the current state of `bevy_rapier`'s API :)
Looking at the examples of [heron](https://github.com/jcornaz/heron/blob/alpha/examples/demo.rs#L56-L65) and [bevy_rapier](https://github.com/dimforge/bevy_rapier/blob/master/bevy_rapier3d/examples/boxes3.rs#L76-L78) it also seems like the basic API of `bevy_rapier` is not more complicated that `heron`'s at this time.

docs(readme): amend comparison to `bevy_rapier` in README.md

---

.github/workflows/build.yml
Cargo.toml
core/Cargo.toml
core/src/collision_from_mesh.rs
core/src/events.rs
core/src/layers.rs
debug/Cargo.toml
debug/src/dim2.rs
debug/src/dim3.rs
debug/src/lib.rs
deny.toml
examples/collision_shapes_in_child_entity.rs
examples/debug_2d.rs
examples/debug_3d.rs
examples/demo.rs
examples/events.rs
examples/layers.rs
examples/quickstart.rs
examples/ray_casting.rs
rapier/Cargo.toml
rapier/src/body.rs
rapier/src/lib.rs
rapier/src/pipeline.rs
rapier/src/shape.rs
rapier/tests/bodies.rs

Bevy 0.8's GlobalTransform is now backed by an Affine3A, in this PR I just naively convert it back to a transform, rotation and scale when needed using the to_scale_rotation_translation() method. This could cause problems (?), as discussed here: https://github.com/dimforge/bevy_rapier/pull/219
I have not taken the time to work out what problems this could cause, but I assume there needs to be some checks done in some places before assigning to the GlobalTransform.

chore(deps): update to bevy 0.8

---

README.md

This adds the latest version (Bevy 0.8 - Heron 4) to the table under supported versions.

docs(readme): add Bevy 0.8 - Heron 4

---

deny.toml

It blocked our CI.
We have to wait until https://github.com/tokio-rs/tracing switched to another dependency, just like in bevy: https://github.com/bevyengine/bevy/pull/5816

ci: ignore RUSTSEC-2021-0139 (ansi_term used by bevy_log is unmaintained)

---

rapier/src/lib.rs
rapier/tests/acceleration.rs
rapier/tests/bodies.rs
rapier/tests/body_types.rs
rapier/tests/children_collision_shapes.rs
rapier/tests/constraints.rs
rapier/tests/damping.rs
rapier/tests/density.rs
rapier/tests/events.rs
rapier/tests/friction.rs
rapier/tests/layers.rs
rapier/tests/resources.rs
rapier/tests/restitution.rs
rapier/tests/sensor_shape.rs
rapier/tests/velocity.rs

If application adds TimePlugin too, this breaks time delta computation. See [this](https://github.com/jcornaz/heron/pull/301/files#r1018542709) comment for more details.
Applications should add all required plugins before adding heron plugins.

Do not add TimePlugin

---

.github/workflows/build.yml
rapier/Cargo.toml
rapier/src/lib.rs

Make the `heron_rapier 4` to re-export most of `heron_rapier 5` (except for `RapierPlugin` which received the breaking change). 
This is also known as the [semver trick](https://github.com/dtolnay/semver-trick), and it makes most code depending on `heron_rapier 4` automatically compatible with `heron_rapier 5` and vice versa.

feat(heron_rapier): compatibility with `heron_rapier` v5
